name: Commit Back

on: [pull_request]

jobs:  
  datecommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: datecommit
        run: |
          echo `date` > date.txt
          git add
          git commit -m "add date"
          git push
